### ISSUE TITLE
Broken CI for REST tests

### ISSUE THREAD

**Issue by marcomicera** [endocode/LCV-CM#1]
[Related GitHub Action job](https://github.com/endocode/LCV-CM/actions/runs/773801125).

**Comment by michelescarlato** [comment]
I would like to run Dockerfile as an action, after every push, and then running [this action](https://github.com/matt-ball/newman-action) upon the Docker container running.
Any hint @marcomicera?

**Comment by marcomicera** [comment]
So [this job](https://github.com/endocode/LCV-CM/actions/runs/773801125) fails as there's no `jobs.<job_id>.using` key in the [GitHub Actions reference page](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions).

**Comment by michelescarlato** [comment]
Thanks to your suggestion, I solved it. 
Now I run Docker with integrated tests.

I tried to separate it into two different jobs, but the second job cannot reach the API server to the 0.0.0.0 IP address (apparently, jobs could run on different machines).
